apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.130
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv-min
      protocol: TCP
      port: 40900
      targetPort: 40900
    - name: pasv-mid
      protocol: TCP
      port: 40901
      targetPort: 40901
    - name: pasv-max
      protocol: TCP
      port: 40902
      targetPort: 40902
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 40900
          name: pasv-min
        - containerPort: 40901
          name: pasv-mid
        - containerPort: 40902
          name: pasv-max